Tweak workflows a little bit

diff --git a/.github/workflows/_build-node-artifact.yaml b/.github/workflows/_build-node-artifact.yaml
--- a/.github/workflows/_build-node-artifact.yaml
+++ b/.github/workflows/_build-node-artifact.yaml
@@ -22,6 +22,14 @@ jobs:
         id: get-branch
         uses: ./.github/actions/get-branch
 
+
+      - name: Check if artifact SFTP details are set
+        if: env.SECRET_ARTIFACT_SFTP_HOST == '' || env.SECRET_ARTIFACT_SFTP_USERNAME == '' || env.SECRET_ARTIFACT_SFTP_PASSWORD == ''
+        run: |
+          echo "Artifact SFTP details are missing"
+          exit 1
+
+
       - name: Build binary
         run: cargo build --release
 
@@ -33,17 +41,13 @@ jobs:
           if-no-files-found: error
           retention-days: 7
 
-      - name: Check if artifact SFTP details are set
-        if: env.SECRET_ARTIFACT_SFTP_HOST == '' || env.SECRET_ARTIFACT_SFTP_USERNAME == '' || env.SECRET_ARTIFACT_SFTP_PASSWORD == ''
-        run: |
-          echo "Artifact SFTP details are missing"
-          exit 1
 
       - name: Upload artifact to SFTP
         run: |
           sudo apt-get install -y sshpass
           sshpass -p "${{ secrets.ARTIFACT_SFTP_PASSWORD }}" \
             scp -o StrictHostKeyChecking=no target/release/node ${{ secrets.ARTIFACT_SFTP_USERNAME }}@${{ secrets.ARTIFACT_SFTP_HOST }}:/home/${{ secrets.ARTIFACT_SFTP_USERNAME }}/node-${{ steps.get-branch.outputs.sha_short }}
+
 
       - name: Configure AWS credentials for S3 bucket with artifacts
         if: env.SECRET_ARTIFACT_S3BUCKET_NAME != '' && env.SECRET_ARTIFACT_S3BUCKET_AWS_ACCESS_KEY_ID != '' && env.SECRET_ARTIFACT_S3BUCKET_AWS_SECRET_ACCESS_KEY != ''
diff --git a/.github/workflows/push-version-tag.yaml b/.github/workflows/push-version-tag.yaml
--- a/.github/workflows/push-version-tag.yaml
+++ b/.github/workflows/push-version-tag.yaml
@@ -29,11 +29,19 @@ jobs:
         id: get-branch
         uses: ./.github/actions/get-branch
 
+
       - name: Check if CI_GITHUB_TOKEN is set
         if: env.SECRET_CI_GITHUB_TOKEN == ''
         run: |
           echo "CI_GITHUB_TOKEN secret is required for this workflow to run"
           exit 1
+
+      - name: Check if docker registry secrets are set
+        if: env.VAR_NODE_REPOSITORY == '' || env.SECRET_NODE_REGISTRY_USERNAME == '' || env.SECRET_NODE_REGISTRY_PASSWORD == ''
+        run: |
+          echo "Docker registry secrets are required for this workflow to run"
+          exit 1
+
 
       - name: Check if commit status is 'success'
         shell: bash
@@ -46,11 +54,6 @@ jobs:
           cat status_output
           cat status_output | grep 'success'
 
-      - name: Check if docker registry secrets are set
-        if: env.VAR_NODE_REPOSITORY == '' || env.SECRET_NODE_REGISTRY_USERNAME == '' || env.SECRET_NODE_REGISTRY_PASSWORD == ''
-        run: |
-          echo "Docker registry secrets are required for this workflow to run"
-          exit 1
 
       - name: Login to docker registry
         uses: docker/login-action@v1
