Tweak asset workflow

diff --git a/.github/workflows/attach-asset-to-release.yaml b/.github/workflows/attach-asset-to-release.yaml
--- a/.github/workflows/attach-asset-to-release.yaml
+++ b/.github/workflows/attach-asset-to-release.yaml
@@ -12,6 +12,7 @@ jobs:
       SECRET_ARTIFACT_SFTP_HOST: ${{ secrets.ARTIFACT_SFTP_HOST }}
       SECRET_ARTIFACT_SFTP_USERNAME: ${{ secrets.ARTIFACT_SFTP_USERNAME }}
       SECRET_ARTIFACT_SFTP_PASSWORD: ${{ secrets.ARTIFACT_SFTP_PASSWORD }}
+      SECRET_CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2.5.0
@@ -19,6 +20,23 @@ jobs:
       - name: Get branch name and commit SHA
         id: get-branch
         uses: ./.github/actions/get-branch
+
+      - name: Check if CI_GITHUB_TOKEN is set
+        if: env.SECRET_CI_GITHUB_TOKEN == ''
+        run: |
+          echo "CI_GITHUB_TOKEN secret is required for this workflow to run"
+          exit 1
+
+      - name: Check if commit status is 'success'
+        shell: bash
+        run: |
+          curl --http1.1 -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.CI_GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/mikogs/project-template-node/commits/${{ steps.get-branch.outputs.sha_long }}/status | jq -r .state > status_output
+          
+          cat status_output
+          cat status_output | grep 'success'
 
       - name: Check if artifact SFTP details are set
         if: env.SECRET_ARTIFACT_SFTP_HOST == '' || env.SECRET_ARTIFACT_SFTP_USERNAME == '' || env.SECRET_ARTIFACT_SFTP_PASSWORD == ''
