Add checks to the push-version-tag workflow

diff --git a/.github/workflows/push-version-tag.yaml b/.github/workflows/push-version-tag.yaml
--- a/.github/workflows/push-version-tag.yaml
+++ b/.github/workflows/push-version-tag.yaml
@@ -18,6 +18,7 @@ jobs:
       VAR_NODE_REGISTRY: ${{ vars.NODE_REGISTRY }}
       SECRET_NODE_REGISTRY_USERNAME: ${{ secrets.NODE_REGISTRY_USER }}
       SECRET_NODE_REGISTRY_PASSWORD: ${{ secrets.NODE_REGISTRY_PASS }}
+      SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2.5.0
@@ -25,6 +26,26 @@ jobs:
       - name: Get branch name and commit SHA
         id: get-branch
         uses: ./.github/actions/get-branch
+
+      - name: Check if GITHUB_TOKEN is set
+        if: env.SECRET_GITHUB_TOKEN == ''
+        run: |
+          echo "GITHUB_TOKEN secret is required for this workflow to run"
+          exit 1
+
+      - name: Wait for status check on the commit
+        id: waitforstatuschecks
+        uses: "WyriHaximus/github-action-wait-for-status@v2"
+        with:
+          checkInterval: 20
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: Check if all statuses for the commit are successful
+        if: steps.id.waitforstatuschecks.outputs.status != 'success'
+        run: |
+          echo "All statuses for commit ${{ steps.get-branch.outputs.sha_short }} must be successful"
+          exit 1
 
       - name: Login to docker registry
         if: env.VAR_NODE_REGISTRY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
