Change the conditions so that docker registry secrets are actually required

diff --git a/.github/workflows/push-version-tag.yaml b/.github/workflows/push-version-tag.yaml
--- a/.github/workflows/push-version-tag.yaml
+++ b/.github/workflows/push-version-tag.yaml
@@ -47,8 +47,13 @@ jobs:
           echo "All statuses for commit ${{ steps.get-branch.outputs.sha_short }} must be successful"
           exit 1
 
+      - name: Check if docker registry secrets are set
+        if: env.VAR_NODE_REGISTRY == '' || env.SECRET_NODE_REGISTRY_USERNAME == '' || env.SECRET_NODE_REGISTRY_PASSWORD == ''
+        run: |
+          echo "docker registry secrets are required for this workflow to run"
+          exit 1
+
       - name: Login to docker registry
-        if: env.VAR_NODE_REGISTRY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
         uses: docker/login-action@v1
         with:
           registry: ${{ vars.NODE_REGISTRY }}
@@ -56,7 +61,6 @@ jobs:
           password: ${{ secrets.SECRET_NODE_REGISTRY_PASSWORD }}
 
       - name: Push docker image to the repository
-        if: env.VAR_NODE_REGISTRY != '' && env.SECRET_NODE_REGISTRY_USERNAME != '' && env.SECRET_NODE_REGISTRY_PASSWORD != ''
         run: |
           docker pull ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.sha_short }}
           docker tag ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.sha_short }} ${{ vars.NODE_REGISTRY }}:{{ steps.get-branch.outputs.branch_name }}
